<script type="text/javascript" src="{{ asset('newsletter/js/env.js') }}"></script>
<script type="text/javascript" src="{{ asset('newsletter/js/bootbox.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('newsletter/js/multiselection.js') }}"></script>
<script type="text/javascript" src="{{ asset('newsletter/js/build.js') }}"></script>
<script type="text/javascript" src="{{ asset('newsletter/js/sorting.js') }}"></script>
<script type="text/javascript" src="{{ asset('newsletter/js/newsletter.js') }}"></script>
<script type="text/javascript" src="{{ asset('newsletter/js/jqColorPicker.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('newsletter/js/utils.js') }}"></script>
<script type="text/javascript" src="{{ asset('newsletter/js/datatables.js') }}"></script>